# Generated by Django 6.0.6 on 2026-07-04 17:35

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SeismicJob',
            fields=[
                ('job_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('complete', 'Complete'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('processing_time_ms', models.IntegerField(blank=True, null=True)),
                ('input_filename', models.CharField(max_length=255)),
                ('result', models.JSONField(blank=True, null=True)),
                ('error_detail', models.CharField(blank=True, max_length=1024, null=True)),
                ('model_version', models.CharField(max_length=50)),
                ('preprocessing_config_version', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
    ]
